(() => {
'use strict';
const $=s=>document.querySelector(s), canvas=$('#board'), ctx=canvas.getContext('2d'), nextCanvas=$('#next'), nctx=nextCanvas.getContext('2d');
const W=10,H=20, colors=['#55e5dc','#f06bba','#f6cf68','#9b83f6','#62d486','#ff9b61','#6ba9ff'];
const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];
let board=[],piece,nextPiece,score=0,lines=0,level=1,over=false,paused=false,last=0,dropTimer=0,raf, audio=null, musicTimer=null;
let prefs={music:true,fx:true,best:0};
try{const s=JSON.parse(localStorage.getItem('tetris-sonique')||'{}');prefs={...prefs,...s}}catch(e){}
$('#best').textContent=prefs.best; $('#musicBtn').classList.toggle('active',prefs.music);$('#fxBtn').classList.toggle('active',prefs.fx);$('#musicBtn').setAttribute('aria-pressed',prefs.music);$('#fxBtn').setAttribute('aria-pressed',prefs.fx);
function save(){try{localStorage.setItem('tetris-sonique',JSON.stringify(prefs))}catch(e){}}
function saveGame(){if(over||!piece)return;prefs.game={board,piece,nextPiece,score,lines,level,paused,dropTimer};save()}
function resetBoard(){board=Array.from({length:H},()=>Array(W).fill(0))}
function randomPiece(){return {shape:shapes[Math.floor(Math.random()*shapes.length)].map(r=>r.slice()),color:Math.floor(Math.random()*7),x:0,y:0}}
function spawn(){piece=nextPiece||randomPiece();nextPiece=randomPiece();piece.x=Math.floor((W-piece.shape[0].length)/2);piece.y=0;if(collides(piece))endGame();drawNext()}
function collides(p,dx=0,dy=0,shape=p.shape){for(let y=0;y<shape.length;y++)for(let x=0;x<shape[y].length;x++)if(shape[y][x]&&(p.y+y+dy>=H||p.x+x+dx<0||p.x+x+dx>=W||(p.y+y+dy>=0&&board[p.y+y+dy][p.x+x+dx])))return true;return false}
function move(dx){if(paused||over)return;if(!collides(piece,dx,0)){piece.x+=dx;sfx(220);draw();saveGame()}}
function rotate(){if(paused||over)return;let sh=Array.from({length:piece.shape[0].length},(_,i)=>piece.shape.map(r=>r[i]).reverse());for(const kick of [0,-1,1,-2,2])if(!collides(piece,kick,0,sh)){piece.shape=sh;piece.x+=kick;sfx(450);draw();saveGame();return}}
function fall(manual=false){if(paused||over)return;if(!collides(piece,0,1)){piece.y++;if(manual){score++;updateHud()}draw();saveGame()}else lock()}
function hardDrop(){if(paused||over)return;let d=0;while(!collides(piece,0,1)){piece.y++;d++}score+=d*2;lock();sfx(120)}
function lock(){piece.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)board[piece.y+y][piece.x+x]=piece.color+1}));sfx(90);clearLines();spawn();updateHud();draw();saveGame()}
function clearLines(){let got=0;board=board.filter(r=>{if(r.every(Boolean)){got++;return false}return true});while(board.length<H)board.unshift(Array(W).fill(0));if(got){lines+=got;score+=[0,100,300,500,800][got]*level;level=1+Math.floor(lines/10);sfx(680);$('#status').textContent=got===1?'Ligne effacée !':got+' lignes effacées !'}}
function endGame(){over=true;paused=false;delete prefs.game;$('#overlay').hidden=false;$('#overlayTitle').textContent='Partie terminée';$('#overlayText').textContent='Ton score : '+score+' · Encore une ?';$('#resumeBtn').textContent='Rejouer';if(score>prefs.best){prefs.best=score;$('#best').textContent=score}save()}
function updateHud(){$('#score').textContent=score;$('#level').textContent=level;$('#lines').textContent=lines}
function draw(){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);const cw=w/W,ch=h/H;ctx.clearRect(0,0,w,h);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--grid');ctx.globalAlpha=.58;ctx.lineWidth=1;for(let x=0;x<=W;x++){ctx.beginPath();ctx.moveTo(x*cw,0);ctx.lineTo(x*cw,h);ctx.stroke()}for(let y=0;y<=H;y++){ctx.beginPath();ctx.moveTo(0,y*ch);ctx.lineTo(w,y*ch);ctx.stroke()}ctx.globalAlpha=1;board.forEach((r,y)=>r.forEach((v,x)=>v&&cell(ctx,x,y,cw,ch,colors[v-1])));if(piece&&!over)piece.shape.forEach((r,y)=>r.forEach((v,x)=>v&&cell(ctx,piece.x+x,piece.y+y,cw,ch,colors[piece.color]))) }
function cell(c,x,y,w,h,color){if(y<0)return;c.fillStyle=color;c.fillRect(x*w+2,y*h+2,w-4,h-4);c.fillStyle='rgba(255,255,255,.2)';c.fillRect(x*w+3,y*h+3,w-6,Math.max(2,h*.1));c.fillStyle='rgba(0,0,0,.12)';c.fillRect(x*w+3,y*h+h-5,w-6,2)}
function drawNext(){nctx.clearRect(0,0,112,72);if(!nextPiece)return;let sh=nextPiece.shape,cw=18,ch=18,ox=(112-sh[0].length*cw)/2,oy=(72-sh.length*ch)/2;sh.forEach((r,y)=>r.forEach((v,x)=>v&&cell(nctx,ox/cw+x,oy/ch+y,cw,ch,colors[nextPiece.color]))) }
function start(){resetBoard();score=0;lines=0;level=1;over=false;paused=false;delete prefs.game;$('#overlay').hidden=true;$('#status').textContent='Prêt à jouer';nextPiece=null;spawn();updateHud();draw();saveGame();startMusic()}
function restoreGame(){const g=prefs.game;if(!g||!Array.isArray(g.board)||g.board.length!==H||!g.board.every(r=>Array.isArray(r)&&r.length===W)||!g.piece||!g.nextPiece)return false;board=g.board.map(r=>r.slice());piece=g.piece;nextPiece=g.nextPiece;score=Number(g.score)||0;lines=Number(g.lines)||0;level=Number(g.level)||1;paused=!!g.paused;over=false;dropTimer=Number(g.dropTimer)||0;last=0;$('#overlay').hidden=!paused;$('#overlayTitle').textContent='Pause';$('#overlayText').textContent='La partie attend ton prochain mouvement.';$('#resumeBtn').textContent='Reprendre';$('#pauseBtn').setAttribute('aria-label',paused?'Reprendre la partie':'Mettre en pause');$('#status').textContent=paused?'Partie en pause':'Partie restaurée';updateHud();drawNext();draw();if(paused)stopMusic();else startMusic();return true}
function pause(){if(over)return;paused=!paused;$('#overlay').hidden=!paused;if(paused){$('#overlayTitle').textContent='Pause';$('#overlayText').textContent='La partie attend ton prochain mouvement.';$('#resumeBtn').textContent='Reprendre';stopMusic();}else startMusic();$('#pauseBtn').setAttribute('aria-label',paused?'Reprendre la partie':'Mettre en pause');saveGame()}
function audioReady(){if(!audio)try{audio=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}
function sfx(freq){if(!prefs.fx)return;audioReady();if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.13)}
function startMusic(){if(!prefs.music||musicTimer)return;audioReady();if(!audio)return;let notes=[261.6,329.6,392,329.6,293.7,349.2,440,349.2],i=0;musicTimer=setInterval(()=>{if(!paused&&!over){const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=notes[i++%notes.length];g.gain.value=.012;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.28)}},480)}function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function loop(t){if(!last)last=t;let dt=t-last;last=t;if(!paused&&!over){dropTimer+=dt;if(dropTimer>Math.max(90,700-(level-1)*55)){fall();dropTimer=0}}draw();raf=requestAnimationFrame(loop)}
[['leftBtn',()=>move(-1)],['rightBtn',()=>move(1)],['downBtn',()=>fall(true)],['rotateBtn',rotate],['dropBtn',hardDrop],['pauseBtn',pause],['resumeBtn',()=>over?start():pause],['newBtn',start]].forEach(([id,fn])=>$('#'+id).addEventListener('click',()=>{audioReady();fn()}));
[['leftBtn',()=>move(-1)],['rightBtn',()=>move(1)]].forEach(([id,fn])=>$('#'+id).addEventListener('touchstart',e=>{e.preventDefault();audioReady();fn()},{passive:false}));
$('#musicBtn').addEventListener('click',()=>{prefs.music=!prefs.music;save();$('#musicBtn').classList.toggle('active',prefs.music);$('#musicBtn').setAttribute('aria-pressed',prefs.music);prefs.music?startMusic():stopMusic()});$('#fxBtn').addEventListener('click',()=>{prefs.fx=!prefs.fx;save();$('#fxBtn').classList.toggle('active',prefs.fx);$('#fxBtn').setAttribute('aria-pressed',prefs.fx)});
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' ','p','P'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='ArrowDown')fall(true);if(e.key==='ArrowUp')rotate();if(e.key===' ')hardDrop();if(e.key==='p'||e.key==='P')pause()});
let touch=null;canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touch={x:t.clientX,y:t.clientY}}, {passive:true});canvas.addEventListener('touchend',e=>{if(!touch)return;const t=e.changedTouches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;touch=null;if(Math.abs(dx)<18&&Math.abs(dy)<18){rotate();return}if(Math.abs(dx)>Math.abs(dy)){move(dx>0?1:-1)}else if(dy>25)hardDrop()},{passive:true});
window.addEventListener('pagehide',saveGame);
if(!restoreGame())start();raf=requestAnimationFrame(loop);
})();