const STORAGE_KEY='domainradar-state-v1';
const EXTENSIONS=['.com','.net','.org','.io','.co','.fr'];
const $=id=>document.getElementById(id);
let state={history:[],lastResults:null};
try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)state={...state,...JSON.parse(saved)}}catch(e){}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function setStatus(message,type=''){const el=$('status');el.hidden=!message;el.className='status '+type;el.textContent=message}
function normalize(value){return value.trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/.*$/,'').replace(/\s/g,'')}
function hasExtension(value){return /\.[a-z]{2,}$/i.test(value)}
function parseParts(answer){const parsed=[];let text=[];if(answer&&Array.isArray(answer.content)){answer.content.forEach(part=>{if(typeof part.text!=='string')return;try{parsed.push(JSON.parse(part.text))}catch(e){text.push(part.text)}})}return{parsed,text:text.join(' ').trim()}}
function flatten(value){if(Array.isArray(value))return value.flatMap(flatten);if(value&&typeof value==='object'){if(Array.isArray(value.results))return flatten(value.results);if(Array.isArray(value.domains))return flatten(value.domains);return [value]}return []}
function mapDomain(item,fallback){if(typeof item==='string')return {domain:item};if(!item||typeof item!=='object')return {domain:fallback};return {domain:item.domain||item.name||item.domain_name||fallback,available:item.available??item.is_available??(item.status==='available'?true:undefined),price:item.price||item.registration_price||item.cost||''}}
function inferAvailable(obj,answer){if(obj.available!==undefined)return !!obj.available;const s=JSON.stringify(obj).toLowerCase()+' '+(answer||'').toLowerCase();if(/unavailable|taken|registered|already|pris|indisponible/.test(s))return false;if(/available|disponible|free|libre/.test(s))return true;return undefined}
function renderResults(items,query,notice=''){const list=$('results');list.innerHTML='';items.forEach(raw=>{const item=mapDomain(raw);item.available=inferAvailable(item,notice);const card=document.createElement('article');card.className='domain-card '+(item.available===true?'available':'taken');const name=document.createElement('div');name.className='domain-name';name.textContent=item.domain||query;const badge=document.createElement('span');badge.className='badge';badge.textContent=item.available===true?'Disponible':item.available===false?'Déjà pris':'Résultat';card.append(name,badge);if(item.price){const price=document.createElement('div');price.className='price';price.textContent='À partir de '+item.price+' USDC';card.append(price)}list.append(card)});$('resultsTitle').textContent=hasExtension(query)?'Vérification directe':'Extensions standards';$('resultCount').textContent=items.length+' résultat'+(items.length>1?'s':'');$('resultsSection').hidden=false;$('shareButton').disabled=items.length===0}
function renderHistory(){const list=$('history');list.innerHTML='';$('clearHistory').hidden=!state.history.length;if(!state.history.length){list.innerHTML='<div class="empty">Vos recherches apparaîtront ici.</div>';return}state.history.slice(0,8).forEach(entry=>{const row=document.createElement('div');row.className='history-item';const b=document.createElement('button');b.type='button';b.textContent=entry.query;b.addEventListener('click',()=>runSearch(entry.query));const date=document.createElement('span');date.className='history-date';date.textContent=new Date(entry.date).toLocaleDateString('fr-FR',{day:'numeric',month:'short'});row.append(b,date);list.append(row)})}
function addHistory(query){state.history=[{query,date:Date.now()},...state.history.filter(x=>x.query!==query)].slice(0,8);save();renderHistory()}
async function runSearch(raw){const query=normalize(raw);if(!query){setStatus('Saisissez un nom de domaine.','error');return}const direct=hasExtension(query);const domains=direct?[query]:EXTENSIONS.map(ext=>query+ext);$('searchButton').disabled=true;setStatus('Interrogation du radar…','loading');addHistory(query);try{const answers=[];for(let i=0;i<domains.length;i++){try{answers.push(await creativeBoard.mcp.call('custom/agentdomainsearch.com/mcp','check_domain',{domain:domains[i]}))}catch(err){answers.push({callError:String(err),content:[]})}}let items=[];let notes=[];answers.forEach((answer,i)=>{if(answer.callError){notes.push(answer.callError);return}const p=parseParts(answer);const raw=p.parsed.flatMap(flatten);if(raw.length)items.push(...raw.map(x=>{const mapped=mapDomain(x,domains[i]);mapped.available=inferAvailable(mapped,p.text);return mapped}));else if(answer&&answer.isError)items.push({domain:domains[i],available:inferAvailable({},p.text)});else if(p.text)items.push({domain:domains[i],available:inferAvailable({},p.text)});if(p.text)notes.push(p.text);if(answer&&answer.isError)notes.push(p.text||'Le service a signalé un résultat particulier.')});state.lastResults={query,items,date:Date.now()};save();renderResults(items,query,notes.join(' '));setStatus('Analyse terminée.','')}catch(err){const reason=String(err);let message='Le service est momentanément indisponible.';if(reason.includes('budget_exhausted'))message='Le quota du service est épuisé pour aujourd’hui. Réessayez demain.';else if(reason.includes('malformed_parameters'))message='La vérification n’a pas pu être comprise par le service.';else if(reason.includes('operation_failed'))message='Le service de domaines est inaccessible pour le moment.';setStatus(message+' ('+reason+')','error')}finally{$('searchButton').disabled=false}}
$('searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch($('domainInput').value)});
$('clearHistory').addEventListener('click',()=>{state.history=[];save();renderHistory()});
$('shareButton').addEventListener('click',async()=>{if(!state.lastResults)return;const text=state.lastResults.items.map(x=>x.domain+' — '+(x.available?'Disponible':'Déjà pris')).join('\n');try{await creativeBoard.share.present({text:'DomainRadar — '+state.lastResults.query+'\n'+text})}catch(e){setStatus('Le partage n’est pas disponible sur cet appareil.','error')}});
renderHistory();
if(state.lastResults){$('domainInput').value=state.lastResults.query;renderResults(state.lastResults.items,state.lastResults.query);setStatus('Derniers résultats restaurés.','')}