const KEY='createur-devis-state-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n)||0);
let state={company:{},quotes:[]}, editingId=null, detailId=null, touch=null;
try{const raw=localStorage.getItem(KEY);if(raw)state=Object.assign(state,JSON.parse(raw));}catch(e){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){toast('Impossible de sauvegarder sur cet appareil');}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2600)}
function dateFr(v){if(!v)return '—';return new Date(v+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'});}
function totals(q){const sub=q.lines.reduce((a,l)=>a+(Number(l.qty)||0)*(Number(l.price)||0),0), rem=sub*(Number(q.discount)||0)/100, net=sub-rem, vat=net*(Number(q.vat)||0)/100;return {sub,rem,net,vat,total:net+vat};}
function nextRef(){const y=new Date().getFullYear();return `DEV-${y}-${String(state.quotes.length+1).padStart(3,'0')}`}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));$('#headerAction').style.display=name==='home'||name==='history'?'block':'none';$('#pageTitle').textContent=name==='company'?'Entreprise':name==='history'?'Historique':name==='editor'?'Nouveau devis':name==='detail'?'Devis':'Devis';$('#app').scrollTop=0;}
function quoteCard(q){const x=totals(q);const d=document.createElement('button');d.className='quote-card';d.type='button';d.dataset.open=q.id;d.innerHTML=`<span class="quote-ref">${esc(q.reference)}</span><span class="quote-total">${euro(x.total)}</span><span class="quote-client">${esc(q.clientName||'Client non renseigné')}</span><span class="quote-date">${dateFr(q.date)}</span>`;return d}
function renderLists(){['recentQuotes','allQuotes'].forEach(id=>{const el=$('#'+id);el.replaceChildren();const arr=id==='recentQuotes'?state.quotes.slice(-3).reverse():[...state.quotes].reverse();if(!arr.length){el.innerHTML='<div class="empty">Aucun devis pour le moment.<br>Votre première proposition est à un geste.</div>';}else arr.forEach(q=>el.append(quoteCard(q)));});}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function fillCompany(){const f=$('#companyForm');Object.entries(state.company||{}).forEach(([k,v])=>{if(f.elements[k]&&k!=='logo')f.elements[k].value=v||'';});$('#logoName').textContent=state.company.logoName?`Logo sélectionné : ${state.company.logoName}`:'';}
function openEditor(q){editingId=q?.id||null;showView('editor');$('#editLabel').textContent=q?'MODIFIER LE DEVIS':'NOUVEAU DEVIS';const f=$('#quoteForm');f.reset();f.elements.reference.value=q?.reference||nextRef();f.elements.date.value=q?.date||new Date().toISOString().slice(0,10);f.elements.validity.value=q?.validity||30;f.elements.discount.value=q?.discount??0;f.elements.vat.value=q?.vat??20;f.elements.clientName.value=q?.clientName||'';f.elements.clientEmail.value=q?.clientEmail||'';f.elements.clientAddress.value=q?.clientAddress||'';f.elements.terms.value=q?.terms||'';f.elements.note.value=q?.note||'';const lines=$('#lineItems');lines.replaceChildren();(q?.lines?.length?q.lines:[{description:'',qty:1,price:0}]).forEach(addLine);updateTotals();}
function addLine(line={description:'',qty:1,price:0}){const el=document.createElement('div');el.className='line';el.innerHTML=`<button type="button" class="remove" aria-label="Supprimer cette ligne">×</button><div class="line-grid"><label>Description<input class="desc" required value="${esc(line.description)}" placeholder="Prestation ou produit"></label><label>Quantité<input class="qty" type="number" min="0" step="0.01" value="${line.qty}"></label></div><div class="line-unit"><label>Prix unitaire HT<input class="price" type="number" min="0" step="0.01" value="${line.price}"></label><div class="line-subtotal"><small>Sous-total</small><strong>${euro((line.qty||0)*(line.price||0))}</strong></div></div>`;el.querySelector('.remove').addEventListener('click',()=>{if($$('.line').length>1){el.remove();updateTotals();}});el.querySelectorAll('input').forEach(i=>i.addEventListener('input',updateTotals));$('#lineItems').append(el);}
function readLines(){return $$('.line').map(el=>({description:el.querySelector('.desc').value,qty:Number(el.querySelector('.qty').value)||0,price:Number(el.querySelector('.price').value)||0}));}
function updateTotals(){const f=$('#quoteForm');const q={lines:readLines(),discount:f.elements.discount?.value||0,vat:f.elements.vat?.value||0};const x=totals(q);$$('.line').forEach(el=>el.querySelector('.line-subtotal strong').textContent=euro((Number(el.querySelector('.qty').value)||0)*(Number(el.querySelector('.price').value)||0)));$('#liveTotals').innerHTML=`<div class="total-row"><span>Sous-total HT</span><strong>${euro(x.sub)}</strong></div><div class="total-row"><span>Remise</span><strong>− ${euro(x.rem)}</strong></div><div class="total-row"><span>TVA (${Number(q.vat)||0} %)</span><strong>${euro(x.vat)}</strong></div><div class="total-row grand"><span>Total TTC</span><strong>${euro(x.total)}</strong></div>`;}
function preview(q){const x=totals(q),c=state.company||{};const company=[c.name?`<strong>${esc(c.name)}</strong>`:'',c.address,[c.zip,c.city].filter(Boolean).join(' '),c.email?'e-mail : '+c.email:'',c.phone?'TEL : '+c.phone:''].filter(Boolean).map((v,i)=>i===0?v:esc(v)).join('<br>');const legal=[c.name,c.legalForm,c.capital?'Capital : '+c.capital:'',c.address,[c.zip,c.city].filter(Boolean).join(' '),c.siret?'SIRET : '+c.siret:'',c.vatNumber?'TVA : '+c.vatNumber:'',c.phone?'TEL : '+c.phone:'',c.email?'e-mail : '+c.email:''].filter(Boolean).map(esc).join(' · ');const logo=c.logo?`<img class="p-logo" src="${esc(c.logo)}" alt="Logo de l’entreprise">`:'';const rows=q.lines.map(l=>`<tr><td>${esc(l.description)}</td><td>${l.qty}</td><td>${euro(l.price)}</td><td>${euro(l.qty*l.price)}</td></tr>`).join('');return `<div class="preview" id="apercu"><div class="p-head"><div><h2>DEVIS</h2><small>${esc(q.reference)} · émis le ${dateFr(q.date)}<br>Valable ${q.validity} jours</small>${q.clientName?`<div style="margin-top:10px"><strong>${esc(q.clientName)}</strong></div>`:''}</div><div style="text-align:right;font-size:12px">${logo}${company||'Votre entreprise'}</div></div><h3>Pour</h3><div>${esc(q.clientName)}${q.clientEmail?'<br>'+esc(q.clientEmail):''}${q.clientAddress?'<br>'+esc(q.clientAddress).replace(/\n/g,'<br>'):''}</div><table><thead><tr><th>Désignation</th><th>Qté</th><th>PU HT</th><th>Total HT</th></tr></thead><tbody>${rows}</tbody></table><div class="p-total"><div><span>Sous-total HT</span><span>${euro(x.sub)}</span></div><div><span>Remise</span><span>− ${euro(x.rem)}</span></div><div><span>TVA (${q.vat} %)</span><span>${euro(x.vat)}</span></div><div class="big"><span>Total TTC</span><span>${euro(x.total)}</span></div></div>${q.terms?`<div class="terms"><b>Conditions de paiement</b><br>${esc(q.terms)}</div>`:''}${q.note?`<div class="terms">${esc(q.note)}</div>`:''}<div class="p-footer">${legal||'Informations légales de l’entreprise'}</div></div>`}
function previewText(q){const x=totals(q);const lines=q.lines.map(l=>`- ${l.description} — ${l.qty} × ${euro(l.price)} = ${euro(l.qty*l.price)}`).join('\n');return `DEVIS ${q.reference}\nÉmis le ${dateFr(q.date)} · Valable ${q.validity} jours\n\nPour : ${q.clientName}${q.clientEmail?'\n'+q.clientEmail:''}${q.clientAddress?'\n'+q.clientAddress:''}\n\n${lines}\n\nSous-total HT : ${euro(x.sub)}\nRemise : − ${euro(x.rem)}\nTVA (${q.vat} %) : ${euro(x.vat)}\nTOTAL TTC : ${euro(x.total)}${q.terms?'\n\nConditions de paiement\n'+q.terms:''}${q.note?'\n\n'+q.note:''}`;}
function openDetail(id){detailId=id;const q=state.quotes.find(x=>x.id===id);if(!q)return;showView('detail');$('#detailContent').innerHTML=`<p class="eyebrow">${esc(q.reference)}</p><h2 id="detailHeading" style="font-family:Georgia,serif;font-size:30px;margin:0 0 4px">${esc(q.clientName)}</h2><p class="muted">${dateFr(q.date)} · ${euro(totals(q).total)} TTC</p>${preview(q)}<div style="display:flex;gap:8px;margin-top:12px"><button class="outline" id="editDetail">Modifier</button><button class="outline" id="duplicateDetail">Dupliquer</button></div><button class="danger" id="deleteDetail">Supprimer ce devis</button>`;const logo=$('#apercu .p-logo');if(logo)logo.addEventListener('error',()=>logo.remove());$('#editDetail').onclick=()=>openEditor(q);$('#duplicateDetail').onclick=()=>{const copy=JSON.parse(JSON.stringify(q));copy.id=crypto.randomUUID?crypto.randomUUID():String(Date.now());copy.reference=nextRef();state.quotes.push(copy);save();renderLists();openDetail(copy.id);toast('Devis dupliqué')};$('#deleteDetail').onclick=()=>{if(confirm('Supprimer ce devis ?')){state.quotes=state.quotes.filter(x=>x.id!==id);save();renderLists();showView('history');toast('Devis supprimé')}}}
function formObject(f){return Object.fromEntries(new FormData(f).entries())}
$('#companyForm').addEventListener('submit',e=>{e.preventDefault();const data=formObject(e.target);data.logo=state.company.logo||'';data.logoName=state.company.logoName||'';state.company=data;save();$('#companySaved').textContent='Coordonnées enregistrées ✓';toast('Entreprise mise à jour');});
$('#logoPicker').addEventListener('click',async()=>{try{const picked=await creativeBoard.media.file();if(picked){state.company.logo=picked.dataUrl;state.company.logoName=picked.name||'fichier importé';save();$('#logoName').textContent=`Logo sélectionné : ${state.company.logoName}`;toast('Logo importé')}}catch(e){toast('Import du logo indisponible : '+e)}});
$('#quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=formObject(e.target);const q={...d,id:editingId||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now())),lines:readLines(),discount:Number(d.discount)||0,vat:Number(d.vat)||0,validity:Number(d.validity)||30};const ix=state.quotes.findIndex(x=>x.id===q.id);if(ix>=0)state.quotes[ix]=q;else state.quotes.push(q);save();renderLists();openDetail(q.id);toast('Devis enregistré');});
$('#addLine').onclick=()=>addLine();$$('#quoteForm input').forEach(i=>i.addEventListener('input',updateTotals));
$('#newQuoteBtn').onclick=()=>openEditor();$('#headerAction').onclick=()=>openEditor();$('#cancelEdit').onclick=()=>showView('home');$('#closeDetail').onclick=()=>showView('history');
$('#app').addEventListener('click',e=>{const card=e.target.closest('.quote-card');if(card)openDetail(card.dataset.open);});
$('#savePdf').onclick=async()=>{try{const q=state.quotes.find(x=>x.id===detailId);const r=await creativeBoard.document.export({format:'pdf',title:q.reference,destination:'save',element:'#apercu'});if(r.completed!==false)toast('PDF prêt à enregistrer')}catch(e){toast('Export PDF indisponible : '+e)}};
$('#shareQuote').onclick=async()=>{try{const q=state.quotes.find(x=>x.id===detailId);const r=await creativeBoard.document.export({format:'pdf',title:q.reference,destination:'share',element:'#apercu'});if(r.completed!==false)toast('PDF prêt à partager')}catch(e){toast('Partage du PDF indisponible : '+e)}};
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{showView(b.dataset.tab);renderLists()}));
$$('.tab').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.tab)));
fillCompany();renderLists();showView('home');
$('#app').addEventListener('touchstart',e=>{const t=e.touches[0];if(t.clientX<=28)touch={x:t.clientX,y:t.clientY,dx:0,locked:false};});$('#app').addEventListener('touchmove',e=>{if(!touch||touch.locked)return;const t=e.touches[0];const dx=t.clientX-touch.x,dy=Math.abs(t.clientY-touch.y);if(dy>Math.abs(dx)){touch.locked=true;return}if(dx>0){touch.dx=dx;$('#app').style.transform=`translateX(${dx}px)`;}});$('#app').addEventListener('touchend',()=>{if(!touch)return;const go=touch.dx>innerWidth*.45;$('#app').style.transition='transform .22s ease';$('#app').style.transform=go?'translateX(100%)':'translateX(0)';if(go){setTimeout(()=>{showView(detailId?'history':'home');$('#app').style.transition='';},180)}else setTimeout(()=>{$('#app').style.transition='';},220);touch=null;});