(function(){
  'use strict';
  var STORAGE_KEY='estimation-immobiliere-state';
  var state={history:[]};
  try{var saved=localStorage.getItem(STORAGE_KEY);if(saved)state=JSON.parse(saved)||state}catch(e){}
  if(!Array.isArray(state.history))state.history=[];
  var currentType='appartement', lastResult=null, historyResultOpen=false;
  var $=function(s){return document.querySelector(s)};
  var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
  var euro=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0});
  var number=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0});
  function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
  function show(id){$$('.screen').forEach(function(x){x.classList.toggle('active',x.id===id)});$$('.tab').forEach(function(x){x.classList.toggle('active',x.dataset.screen===id)});window.scrollTo(0,0)}
  function extras(){var box=$('#extraFields');box.replaceChildren();var label=document.createElement('label'),input=document.createElement('input');label.htmlFor='extra';if(currentType==='maison'){label.textContent='Extérieur';input.id='extra';input.placeholder='Jardin, terrasse, garage…'}else{label.textContent='Atouts';input.id='extra';input.placeholder='Balcon, ascenseur, parking…'}box.append(label,input)}
  $$('.segment').forEach(function(btn){btn.addEventListener('click',function(){currentType=btn.dataset.type;$$('.segment').forEach(function(b){var yes=b===btn;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes)});extras()})});extras();
  function commune(address){var clean=address.trim();var parts=clean.split(',');var place=parts[parts.length-1].trim();var match=place.match(/(?:\b\d{5}\b\s*)?(.+)$/);return (match?match[1]:place)||'Votre commune'}
  function benchmark(address,type){var a=address.toLowerCase(), base=type==='maison'?3200:3950;var names=[['paris',10200],['lyon',5200],['marseille',3500],['bordeaux',4800],['nantes',4100],['toulouse',3700],['lille',3300],['montpellier',3900],['strasbourg',4000],['rennes',4300],['nice',6100]];for(var i=0;i<names.length;i++)if(a.indexOf(names[i][0])>-1)return type==='maison'?Math.round(names[i][1]*.86):names[i][1];var digits=(a.match(/\d/g)||[]).reduce(function(x,n){return x+Number(n)},0);return base+(digits%7-3)*100}
  function calculate(){var address=$('#address').value.trim(),surface=Number($('#surface').value),rooms=Number($('#rooms').value),condition=$('#condition').value;if(!address||!surface||surface<9){$('#address').focus();if(!address)$('#address').setCustomValidity('Saisissez une adresse');else $('#address').setCustomValidity('');return null}$('#address').setCustomValidity('');var per=benchmark(address,currentType),conditionFactor={renover:.78,rafraichir:.9,bon:1,excellent:1.08}[condition],roomFactor=1+(Math.min(6,rooms)-3)*.018;var central=Math.round(surface*per*conditionFactor*roomFactor/100)*100,extra=$('#extra')?$('#extra').value.trim():'';var low=Math.round(central*.94/100)*100,high=Math.round(central*1.07/100)*100;return{address:address,commune:commune(address),surface:surface,rooms:rooms,type:currentType,condition:condition,extra:extra,perM2:Math.round(central/surface),central:central,low:low,high:high,date:new Date().toISOString()}}
  function renderResult(r){lastResult=r;currentType=r.type;$('#resultAddress').textContent=r.address;$('#priceRange').textContent=euro.format(r.low)+' – '+euro.format(r.high);$('#pricePerM2').textContent=number.format(r.perM2)+' € / m²';$('#centralPrice').textContent=euro.format(r.central);$('#resultSurface').textContent=number.format(r.surface)+' m²';$('#resultType').textContent=r.type==='maison'?'Maison':'Appartement';$('#sectorSubtitle').textContent=r.commune+' · repères communaux';var sale1=Math.round(r.perM2*.96/50)*50,sale2=Math.round(r.perM2*1.04/50)*50;var box=$('#sectorData');box.replaceChildren();var grid=document.createElement('div');grid.className='sector-grid';[['Prix médian / m²',number.format(r.perM2)+' €'],['Ventes récentes','Repère local'],['Type étudié',r.type==='maison'?'Maison':'Appartement'],['Tendance','À confirmer']].forEach(function(item){var d=document.createElement('div');d.className='sector-stat';var s=document.createElement('span');s.textContent=item[0];var st=document.createElement('strong');st.textContent=item[1];d.append(s,st);grid.append(d)});var note=document.createElement('p');note.className='sales-note';note.textContent='Les ventes autour de '+r.commune+' sont proposées comme repères indicatifs hors connexion. Pour une valeur opposable, consultez les transactions DVF à jour et un professionnel.';box.append(grid,note);show('resultScreen')}
  $('#estimateForm').addEventListener('submit',function(e){e.preventDefault();var r=calculate();if(!r)return; if($('#keepHistory').checked){state.history.unshift(r);state.history=state.history.slice(0,20);persist()}renderResult(r)});
  $('#newEstimate').addEventListener('click',function(){if(historyResultOpen){history.back()}else show('estimateScreen')});
  function renderHistory(){var box=$('#historyList');box.replaceChildren();if(!state.history.length){var empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='Aucune estimation conservée pour le moment.<br>Votre prochain repère apparaîtra ici.';box.append(empty);return}state.history.forEach(function(r){var item=document.createElement('article');item.className='history-item';item.setAttribute('tabindex','0');var head=document.createElement('header');var h3=document.createElement('h3');h3.textContent=r.commune;var time=document.createElement('time');time.textContent=new Date(r.date).toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'});var remove=document.createElement('button');remove.type='button';remove.className='history-delete';remove.setAttribute('aria-label','Supprimer cette estimation');remove.textContent='Supprimer';head.append(h3,time,remove);var address=document.createElement('p');address.className='history-address';address.textContent=r.address;var p=document.createElement('p');p.textContent=(r.type==='maison'?'Maison':'Appartement')+' · '+r.surface+' m² · '+r.rooms+' pièces';var price=document.createElement('div');price.className='history-price';price.textContent=euro.format(r.central);item.append(head,address,p,price);item.addEventListener('click',function(e){if(e.target===remove)return;historyResultOpen=true;history.pushState({screen:'historyResult'},'',window.location.pathname+window.location.search+'#result');renderResult(r)});item.addEventListener('keydown',function(e){if((e.key==='Enter'||e.key===' ')&&e.target===item){e.preventDefault();historyResultOpen=true;history.pushState({screen:'historyResult'},'',window.location.pathname+window.location.search+'#result');renderResult(r)}});remove.addEventListener('click',function(e){e.stopPropagation();if(remove.dataset.confirming==='true'){var position=state.history.indexOf(r);if(position>-1){state.history.splice(position,1);persist();renderHistory()}return}remove.dataset.confirming='true';remove.textContent='Confirmer ?';remove.setAttribute('aria-label','Confirmer la suppression');setTimeout(function(){if(remove.dataset.confirming==='true'){remove.dataset.confirming='false';remove.textContent='Supprimer';remove.setAttribute('aria-label','Supprimer cette estimation')}},3000)});box.append(item)})}
  $('#shareResult').addEventListener('click',async function(){if(!lastResult)return;var text='Mon estimation immobilière pour le bien situé au '+lastResult.address+' ('+lastResult.commune+') : '+euro.format(lastResult.low)+' à '+euro.format(lastResult.high)+' ('+number.format(lastResult.perM2)+' €/m²). Estimation indicative.';try{await window.creativeBoard.share.present({text:text})}catch(e){this.textContent='Partage indisponible';setTimeout(()=>this.textContent='↗ Partager le résultat',2200)}});
  $('#shareHeader').addEventListener('click',async function(){try{await window.creativeBoard.share.present({text:'Estimation immobilière — un repère local de valeur pour votre bien en France.'})}catch(e){}});
  var edgeSwipe={tracking:false,locked:false,startX:0,startY:0};
  function resetResultPosition(){var screen=$('#resultScreen');screen.style.transition='transform .24s ease-out';screen.style.transform='translateX(0)';setTimeout(function(){screen.style.transition='';screen.style.transform=''},240)}
  document.addEventListener('touchstart',function(e){if(!historyResultOpen||e.touches.length!==1)return;var touch=e.touches[0];if(touch.clientX>28)return;edgeSwipe.tracking=true;edgeSwipe.locked=false;edgeSwipe.startX=touch.clientX;edgeSwipe.startY=touch.clientY;$('#resultScreen').style.transition='none'},{passive:true});
  document.addEventListener('touchmove',function(e){if(!edgeSwipe.tracking||e.touches.length!==1)return;var touch=e.touches[0],dx=touch.clientX-edgeSwipe.startX,dy=touch.clientY-edgeSwipe.startY;if(!edgeSwipe.locked&&Math.abs(dy)>Math.abs(dx)){edgeSwipe.tracking=false;resetResultPosition();return}if(dx<0){edgeSwipe.tracking=false;resetResultPosition();return}edgeSwipe.locked=true;e.preventDefault();$('#resultScreen').style.transform='translateX('+dx+'px)'},{passive:false});
  document.addEventListener('touchend',function(){if(!edgeSwipe.tracking)return;var screen=$('#resultScreen'),distance=parseFloat(screen.style.transform.replace(/[^0-9.-]/g,''))||0;edgeSwipe.tracking=false;if(edgeSwipe.locked&&distance>window.innerWidth*.5){screen.style.transition='transform .2s ease-out';screen.style.transform='translateX(100%)';setTimeout(function(){history.back()},180)}else resetResultPosition()});
  document.addEventListener('touchcancel',function(){if(edgeSwipe.tracking){edgeSwipe.tracking=false;resetResultPosition()}});
  window.addEventListener('popstate',function(){if(historyResultOpen){historyResultOpen=false;resetResultPosition();renderHistory();show('historyScreen')}});
  $$('.tab').forEach(function(tab){tab.addEventListener('click',function(){var id=tab.dataset.screen;if(historyResultOpen){historyResultOpen=false;history.replaceState(null,'',window.location.pathname+window.location.search)}if(id==='historyScreen')renderHistory();show(id)})});
  renderHistory();
})();